<?php
require_once __DIR__.'/config/config.php';
$lang=(($_GET['lang']??'ar')==='en')?'en':'ar';
try{$services=db()->query("SELECT * FROM services WHERE enabled=1 ORDER BY sort_order,id")->fetchAll();$portfolio=db()->query("SELECT * FROM portfolio WHERE enabled=1 ORDER BY sort_order,id")->fetchAll();$about=db()->query("SELECT * FROM sections WHERE section_key='about' AND enabled=1 ORDER BY id LIMIT 1")->fetch()?:[];$menus=db()->query("SELECT * FROM menu_items WHERE enabled=1 AND location='header' ORDER BY sort_order,id")->fetchAll();$socials=db()->query("SELECT * FROM social_links WHERE enabled=1 ORDER BY sort_order,id")->fetchAll();}catch(Throwable $e){http_response_code(500);exit('Database error: '.e($e->getMessage()));}
function rich($v){$x=e($v);return str_replace(['&lt;em&gt;','&lt;/em&gt;'],['<em>','</em>'],$x);}
require __DIR__.'/includes/site-header.php';
?>
<main>
<section id="home" class="hero"><div class="hero-orb orb-one"></div><div class="hero-orb orb-two"></div><div class="hero-grid"></div><div class="container hero-inner"><div class="hero-copy reveal"><div class="eyebrow glass-soft"><span>✦</span><span><?=e(setting($lang==='ar'?'heroBadge_ar':'heroBadge_en'))?></span></div><h1><?=rich(setting($lang==='ar'?'heroTitle_ar':'heroTitle_en'))?></h1><p><?=e(setting($lang==='ar'?'heroText_ar':'heroText_en'))?></p><div class="hero-actions"><a class="btn btn-gold" href="#work"><?=$lang==='ar'?'شاهد أعمالنا ↗':'View Our Work ↗'?></a><a class="btn btn-glass" href="#services"><?=$lang==='ar'?'استكشف خدماتنا':'Explore Services'?></a></div></div><div class="hero-panel glass reveal"><div class="panel-top"><span class="status-dot"></span><span><?=$lang==='ar'?'حلول مصممة حول علامتك':'Solutions built around your brand'?></span></div><div class="metric"><strong>+12</strong><span><?=$lang==='ar'?'عاماً من الخبرة':'Years of Experience'?></span></div><div class="panel-divider"></div><div class="consult"><div><small><?=$lang==='ar'?'استشارة تسويقية':'Marketing Consultation'?></small><strong>$15 <span><?=$lang==='ar'?' / ساعة':' / hour'?></span></strong></div><a href="https://wa.me/<?=e(preg_replace('/\D+/','',setting('whatsapp',setting('phone'))))?>" target="_blank" rel="noopener">WhatsApp ↗</a></div></div></div><a class="scroll-cue" href="#services" aria-label="<?=$lang==='ar'?'اكتشف المزيد':'Discover more'?>"><span class="scroll-arrow">↓</span><small><?=$lang==='ar'?'اكتشف المزيد':'Discover more'?></small></a></section>
<div class="ticker"><div><?=$lang==='ar'?'هوية بصرية · تصميم · تسويق رقمي · صناعة محتوى · استراتيجيات نمو ·':'Brand Identity · Design · Digital Marketing · Content · Growth Strategy ·'?></div></div>
<section id="services" class="section services"><div class="container"><div class="section-head reveal"><span class="section-kicker">01 / <b><?=$lang==='ar'?'خدماتنا':'Services'?></b></span><h2><?=rich($lang==='ar'?'حلول متكاملة، <em>بهوية تصنع الفرق.</em>':'Integrated solutions, <em>designed to make a difference.</em>')?></h2><p><?=$lang==='ar'?'نحوّل الإبداع إلى حلول بصرية وتسويقية تخدم أهداف علامتك التجارية.':'We turn creativity into visual and marketing solutions built around your brand goals.'?></p></div><div class="service-grid"><?php foreach($services as $i=>$x):?><article class="service-card glass reveal" data-work-target="work-<?=$i?>"><span class="service-no">0<?=($i+1)?></span><div class="icon">✦</div><h3><?=e($lang==='ar'?$x['title_ar']:$x['title_en'])?></h3><p><?=e($lang==='ar'?$x['description_ar']:$x['description_en'])?></p></article><?php endforeach;?></div></div></section>
<section id="about" class="section about"><div class="container"><div class="about-card glass reveal"><span class="section-kicker">02 / <b><?=$lang==='ar'?'من نحن':'About'?></b></span><h2><?=rich($lang==='ar'?'خبرة إبداعية، <em>بعقلية تسويقية.</em>':'Creative expertise, <em>with a marketing mindset.</em>')?></h2><?php if(!empty($about['image'])):?><img class="about-image" src="<?=e($about['image'])?>" alt="<?=e($about['title_ar']??'Thaer Media')?>"><?php endif;?><p><?=e($lang==='ar'?($about['content_ar']??''):($about['content_en']??''))?></p><div class="about-points"><span>✦ <b><?=$lang==='ar'?'أكثر من 12 عاماً من الخبرة':'12+ years of experience'?></b></span><span>✦ <b><?=$lang==='ar'?'حلول مخصصة لكل علامة':'Tailored solutions for every brand'?></b></span><span>✦ <b><?=$lang==='ar'?'تصميم يفهم التسويق':'Design that understands marketing'?></b></span><span>✦ <b><?=$lang==='ar'?'خدمة عربية وإنجليزية':'Arabic & English service'?></b></span></div></div></div></section>
<section id="work" class="section work"><div class="container"><div class="section-head reveal"><span class="section-kicker">03 / <b><?=$lang==='ar'?'أعمالنا':'Selected Work'?></b></span><h2><?=rich($lang==='ar'?'أعمال تُظهر <em>ما نستطيع صنعه.</em>':'Work that shows <em>what we can create.</em>')?></h2><p><?=$lang==='ar'?'نماذج مختارة من التصميم والهوية والمحتوى والحملات الإعلانية.':'A curated selection of design, branding, content, and advertising work.'?></p></div><div class="portfolio-grid"><?php foreach($portfolio as $i=>$x):?><a id="work-<?=$i?>" class="portfolio-card p<?=($i%6)+1?> glass reveal" href="<?=e($x['url']?:($x['image']?:'#'))?>" <?=!empty($x['url'])?'target="_blank" rel="noopener"':''?>><?php if(!empty($x['image'])):?><img src="<?=e($x['image'])?>" alt="<?=e($x['title'])?>"><?php endif;?><span class="portfolio-tag"><?=e($x['title'])?></span></a><?php endforeach;?></div><a class="all-work" href="https://www.behance.net/gallery/215783633/My-Portfolio-2022-2024" target="_blank" rel="noopener"><?=$lang==='ar'?'شاهد المحفظة كاملة على Behance ↗':'View the full portfolio on Behance ↗'?></a></div></section>
<section class="section contact"><div class="container contact-wrap"><div class="contact-copy reveal"><span class="section-kicker">04 / <b><?=$lang==='ar'?'تواصل معنا':'Contact'?></b></span><h2><?=rich($lang==='ar'?'جاهز نبدأ؟ <em>خلّينا نحكي.</em>':'Ready to start? <em>Let’s talk.</em>')?></h2><p><?=$lang==='ar'?'كل تفاصيل التواصل والنموذج أصبحت في صفحة مستقلة لتجربة أكثر ترتيباً.':'All contact details and the inquiry form are now on a dedicated page for a cleaner experience.'?></p><div class="contact-links"><a class="contact-link glass" href="contact.php?lang=<?=$lang?>"><span><?=$lang==='ar'?'صفحة التواصل':'Contact page'?></span><b><?=$lang==='ar'?'افتح صفحة تواصل معنا ↗':'Open Contact Page ↗'?></b></a></div></div></div></section>
</main><?php require __DIR__.'/includes/site-footer.php';?>
