<?php
require_once __DIR__.'/config/config.php';
$lang=(($_GET['lang']??'ar')==='en')?'en':'ar';
try {
    $services=db()->query("SELECT * FROM services WHERE enabled=1 ORDER BY sort_order,id")->fetchAll();
    $portfolio=db()->query("SELECT * FROM portfolio WHERE enabled=1 ORDER BY sort_order,id")->fetchAll();
    $about=db()->query("SELECT * FROM sections WHERE section_key='about' AND enabled=1 ORDER BY id LIMIT 1")->fetch() ?: [];
    $menus=db()->query("SELECT * FROM menu_items WHERE enabled=1 AND location='header' ORDER BY sort_order,id")->fetchAll();
    $socials=db()->query("SELECT * FROM social_links WHERE enabled=1 ORDER BY sort_order,id")->fetchAll();
} catch(Throwable $e) { http_response_code(500); exit('Database error: '.e($e->getMessage())); }
require __DIR__.'/includes/site-header.php';
?>
<main>
<section class="hero hero-premium"><div class="hero-copy reveal"><span class="eyebrow"><?=e(setting($lang==='ar'?'heroBadge_ar':'heroBadge_en'))?></span><h1><?=e(setting($lang==='ar'?'heroTitle_ar':'heroTitle_en'))?></h1><p><?=e(setting($lang==='ar'?'heroText_ar':'heroText_en'))?></p><div class="cta"><a class="btn magnetic" href="#portfolio"><?=$lang==='ar'?'شاهد أعمالنا ↗':'View our work ↗'?></a><a class="text-link" href="#services"><?=$lang==='ar'?'استكشف خدماتنا':'Explore services'?></a></div></div>
<div class="hero-visual reveal"><div class="visual-glow"></div><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="infographic"><div class="infographic-top"><span>THAER</span><i>MEDIA</i></div><div class="metric"><b>+12</b><span><?=$lang==='ar'?'سنة خبرة':'Years experience'?></span></div><div class="bars"><?php foreach([42,68,54,86,72,96] as $h):?><i style="--h:<?=$h?>%"></i><?php endforeach;?></div><div class="mini-labels"><span>BRAND</span><span>DESIGN</span><span>GROWTH</span></div></div><div class="float-card fc-one">✦ <?=$lang==='ar'?'إبداع':'Creative'?></div><div class="float-card fc-two">↗ <?=$lang==='ar'?'نتائج':'Results'?></div></div></section>
<div class="ticker"><div><?=$lang==='ar'?'هوية بصرية · تصميم · تسويق رقمي · صناعة محتوى · استراتيجيات نمو ·':'Brand Identity · Design · Digital Marketing · Content · Growth Strategy ·'?></div></div>
<section id="services" class="section"><div class="section-head reveal"><span>01 / <?=$lang==='ar'?'خدماتنا':'Services'?></span><h2><?=$lang==='ar'?'حلول متكاملة، بهوية تصنع الفرق.':'Integrated solutions with an identity that makes a difference.'?></h2></div><div class="grid services"><?php foreach($services as $i=>$x):?><article class="service-card reveal"><div class="service-index">0<?=($i+1)?></div><?php if(!empty($x['image'])):?><div class="image-wrap"><img src="<?=e($x['image'])?>" alt="<?=e($x['title_ar'])?>"></div><?php else:?><div class="service-icon">✦</div><?php endif;?><h3><?=e($lang==='ar'?$x['title_ar']:$x['title_en'])?></h3><p><?=e($lang==='ar'?$x['description_ar']:$x['description_en'])?></p><span class="arrow">↗</span></article><?php endforeach;?></div></section>
<section id="about" class="section split about-premium"><div class="reveal"><span>02 / <?=$lang==='ar'?'من نحن':'About'?></span><h2><?=e($lang==='ar'?'من نحن':'About us')?></h2></div><div class="reveal"><?php if(!empty($about['image'])):?><img class="about-image" src="<?=e($about['image'])?>" alt="<?=e($about['title_ar']??'Thaer Media')?>"><?php endif;?><p><?=e($lang==='ar'?($about['content_ar']??''):($about['content_en']??''))?></p><div class="about-pills"><span>12+ <?=$lang==='ar'?'سنة':'Years'?></span><span>AR / EN</span><span>360° <?=$lang==='ar'?'حلول':'Solutions'?></span></div></div></section>
<section id="portfolio" class="section portfolio-section"><div class="section-head reveal"><span>03 / <?=$lang==='ar'?'أعمالنا':'Work'?></span><h2><?=$lang==='ar'?'أعمال تُظهر ما نستطيع صنعه.':'Work that shows what we can create.'?></h2></div><div class="portfolio"><?php foreach($portfolio as $x):?><a class="work reveal" href="<?=e($x['url']?:'#')?>" <?=!empty($x['url'])?'target="_blank" rel="noopener"':''?>><?php if(!empty($x['image'])):?><div class="work-media"><img src="<?=e($x['image'])?>" alt="<?=e($x['title'])?>"><span>VIEW ↗</span></div><?php else:?><div class="work-media placeholder"><span>THAER MEDIA</span></div><?php endif;?><div><small><?=e($x['category'])?></small><h3><?=e($x['title'])?></h3><p><?=e($x['description'])?></p></div></a><?php endforeach;?></div></section>
<section id="contact" class="contact contact-premium"><div class="reveal"><span>04 / <?=$lang==='ar'?'تواصل معنا':'Contact'?></span><h2><?=$lang==='ar'?'جاهز نبدأ؟ خلّينا نحكي.':'Ready to start? Let’s talk.'?></h2></div><div class="contact-box reveal"><a class="magnetic" href="https://wa.me/<?=e(preg_replace('/\D+/','',setting('whatsapp')))?>">WhatsApp · <?=e(setting('phone'))?> ↗</a><?php if(setting('email')):?><a href="mailto:<?=e(setting('email'))?>"><?=e(setting('email'))?> ↗</a><?php endif;?></div></section>
</main><?php require __DIR__.'/includes/site-footer.php';?>
