<?php
require_once __DIR__.'/../config/config.php';
admin_required();
$message=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    verify_csrf(); $a=$_POST['action']??'';
    if($a==='settings'){
      foreach(['siteName','phone','whatsapp','email','heroBadge_ar','heroBadge_en','heroTitle_ar','heroTitle_en','heroText_ar','heroText_en','layout','menuPosition','mode','primary','accent','lightBg','darkBg','lightText','darkText'] as $k){if(isset($_POST[$k]))save_setting($k,trim((string)$_POST[$k]));}
      if(!empty($_FILES['logo']['name'])) save_setting('logo',upload_media('logo'));
      $message='تم حفظ الإعدادات.';
    } elseif($a==='about_save'){
      $image=$_POST['current_image']??''; if(!empty($_FILES['file']['name']))$image=upload_media('file');
      db()->prepare("UPDATE sections SET title_ar=?,title_en=?,content_ar=?,content_en=?,image=?,enabled=?,sort_order=? WHERE section_key='about'")->execute([$_POST['title_ar']??'',$_POST['title_en']??'',$_POST['content_ar']??'',$_POST['content_en']??'',$image,isset($_POST['enabled'])?1:0,(int)($_POST['sort_order']??2)]);
      $message='تم حفظ قسم من نحن.';
    } elseif($a==='service_save'){
      $id=(int)($_POST['id']??0); $image=$_POST['current_image']??''; if(!empty($_FILES['file']['name']))$image=upload_media('file');
      $d=[trim($_POST['title_ar']??''),trim($_POST['title_en']??''),trim($_POST['description_ar']??''),trim($_POST['description_en']??''),$image,isset($_POST['enabled'])?1:0,(int)($_POST['sort_order']??0)];
      if($id){$d[]=$id;db()->prepare("UPDATE services SET title_ar=?,title_en=?,description_ar=?,description_en=?,image=?,enabled=?,sort_order=? WHERE id=?")->execute($d);}else db()->prepare("INSERT INTO services(title_ar,title_en,description_ar,description_en,image,enabled,sort_order) VALUES(?,?,?,?,?,?,?)")->execute($d);
      $message='تم حفظ الخدمة.';
    } elseif($a==='service_delete'){db()->prepare('DELETE FROM services WHERE id=?')->execute([(int)$_POST['id']]);$message='تم حذف الخدمة.';}
    elseif($a==='portfolio_save'){
      $id=(int)($_POST['id']??0); $image=$_POST['current_image']??''; if(!empty($_FILES['file']['name']))$image=upload_media('file');
      $d=[trim($_POST['title']??''),trim($_POST['category']??''),trim($_POST['description']??''),$image,trim($_POST['url']??''),isset($_POST['enabled'])?1:0,(int)($_POST['sort_order']??0)];
      if($id){$d[]=$id;db()->prepare("UPDATE portfolio SET title=?,category=?,description=?,image=?,url=?,enabled=?,sort_order=? WHERE id=?")->execute($d);}else db()->prepare("INSERT INTO portfolio(title,category,description,image,url,enabled,sort_order) VALUES(?,?,?,?,?,?,?)")->execute($d);
      $message='تم حفظ العمل.';
    } elseif($a==='portfolio_delete'){db()->prepare('DELETE FROM portfolio WHERE id=?')->execute([(int)$_POST['id']]);$message='تم حذف العمل.';}
    elseif($a==='media_upload'){upload_media('file');$message='تم رفع الملف بنجاح.';}
    elseif($a==='media_delete'){
      $q=db()->prepare('SELECT path FROM media WHERE id=?');$q->execute([(int)$_POST['id']]);$m=$q->fetch();if($m){$p=dirname(__DIR__).DIRECTORY_SEPARATOR.str_replace('/',DIRECTORY_SEPARATOR,$m['path']);if(is_file($p))@unlink($p);db()->prepare('DELETE FROM media WHERE id=?')->execute([(int)$_POST['id']]);}$message='تم حذف الملف.';
    }
    elseif($a==='menu_save'){$id=(int)($_POST['id']??0);$d=[trim($_POST['label_ar']??''),trim($_POST['label_en']??''),trim($_POST['url']??''),trim($_POST['location']??'header'),isset($_POST['enabled'])?1:0,(int)($_POST['sort_order']??0)];if($id){$d[]=$id;db()->prepare("UPDATE menu_items SET label_ar=?,label_en=?,url=?,location=?,enabled=?,sort_order=? WHERE id=?")->execute($d);}else db()->prepare("INSERT INTO menu_items(label_ar,label_en,url,location,enabled,sort_order) VALUES(?,?,?,?,?,?)")->execute($d);$message='تم حفظ القائمة.';}
    elseif($a==='menu_delete'){db()->prepare('DELETE FROM menu_items WHERE id=?')->execute([(int)$_POST['id']]);$message='تم حذف الرابط.';}
    elseif($a==='social_save'){$id=(int)($_POST['id']??0);$d=[trim($_POST['name']??''),trim($_POST['url']??''),trim($_POST['icon']??''),isset($_POST['enabled'])?1:0,(int)($_POST['sort_order']??0)];if($id){$d[]=$id;db()->prepare("UPDATE social_links SET name=?,url=?,icon=?,enabled=?,sort_order=? WHERE id=?")->execute($d);}else db()->prepare("INSERT INTO social_links(name,url,icon,enabled,sort_order) VALUES(?,?,?,?,?)")->execute($d);$message='تم حفظ الشبكة.';}
    elseif($a==='social_delete'){db()->prepare('DELETE FROM social_links WHERE id=?')->execute([(int)$_POST['id']]);$message='تم حذف الشبكة.';}
    elseif($a==='page_save'){$id=(int)($_POST['id']??0);$d=[trim($_POST['slug']??''),trim($_POST['title_ar']??''),trim($_POST['title_en']??''),$_POST['content_ar']??'',$_POST['content_en']??'',isset($_POST['enabled'])?1:0,(int)($_POST['sort_order']??0)];if($id){$d[]=$id;db()->prepare("UPDATE pages SET slug=?,title_ar=?,title_en=?,content_ar=?,content_en=?,enabled=?,sort_order=? WHERE id=?")->execute($d);}else db()->prepare("INSERT INTO pages(slug,title_ar,title_en,content_ar,content_en,enabled,sort_order) VALUES(?,?,?,?,?,?,?)")->execute($d);$message='تم حفظ الصفحة.';}
    elseif($a==='page_delete'){db()->prepare('DELETE FROM pages WHERE id=?')->execute([(int)$_POST['id']]);$message='تم حذف الصفحة.';}
  }catch(Throwable $ex){$error=$ex->getMessage();}
}
$s=settings();$about=db()->query("SELECT * FROM sections WHERE section_key='about' LIMIT 1")->fetch()?:[];$services=db()->query('SELECT * FROM services ORDER BY sort_order,id')->fetchAll();$portfolio=db()->query('SELECT * FROM portfolio ORDER BY sort_order,id')->fetchAll();$media=db()->query('SELECT * FROM media ORDER BY id DESC')->fetchAll();$menus=db()->query('SELECT * FROM menu_items ORDER BY location,sort_order,id')->fetchAll();$socials=db()->query('SELECT * FROM social_links ORDER BY sort_order,id')->fetchAll();$pages=db()->query('SELECT * FROM pages ORDER BY sort_order,id')->fetchAll();
function checked($v){return $v?'checked':'';}
?>
<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Thaer Media — Admin</title><link rel="stylesheet" href="assets/admin.css"><style>.preview-img{width:110px;height:75px;object-fit:cover;border-radius:10px;border:1px solid #ddd}.upload-row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.hint{color:#777;font-size:12px}.tabs{position:sticky;top:0;z-index:10;background:#f6f7fb;padding:10px 0;display:flex;gap:8px;overflow:auto}.tabs a{padding:9px 13px;background:#fff;border-radius:10px;border:1px solid #e5e7eb;white-space:nowrap}.file-input{border:2px dashed #d6d9e0;padding:18px;border-radius:14px;background:#fafafa}.media-grid{grid-template-columns:repeat(auto-fill,minmax(170px,1fr))!important}.media-card img{height:130px!important;object-fit:cover}</style></head><body>
<header class="top"><div class="brand">Thaer Media <small>ADMIN</small></div><div class="top-actions"><a href="../index.php" target="_blank">عرض الموقع ↗</a><a href="logout.php">خروج</a></div></header><div class="app"><aside class="side"><div class="profile"><div class="avatar">TM</div><b>مدير الموقع</b><span>Administrator</span></div><?php foreach([['dashboard','⌂ لوحة التحكم'],['design','🎨 التصميم'],['home','🏠 الرئيسية'],['about','👤 من نحن'],['services','🧩 الخدمات'],['portfolio','🖼️ الأعمال والصور'],['media','📁 مدير الملفات'],['pages','📄 الصفحات'],['menus','☰ القوائم'],['social','🔗 السوشيال']] as $n):?><a href="#<?=$n[0]?>"><?=$n[1]?></a><?php endforeach;?></aside><main class="content">
<?php if($message):?><div class="success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert"><?=e($error)?></div><?php endif;?>
<div class="tabs"><?php foreach(['design'=>'التصميم','home'=>'الرئيسية','about'=>'من نحن','services'=>'الخدمات','portfolio'=>'الأعمال','media'=>'الملفات','pages'=>'الصفحات','menus'=>'القوائم','social'=>'السوشيال'] as $id=>$label):?><a href="#<?=$id?>"><?=$label?></a><?php endforeach;?></div>
<section id="dashboard" class="hero-admin"><div><span>مرحبًا بك 👋</span><h1>لوحة تحكم Thaer Media</h1><p>إدارة سهلة للمحتوى والتصميم والصور — بدون كتابة روابط الصور.</p></div><a class="preview" href="../index.php" target="_blank">فتح الموقع</a></section>
<div class="stats"><div><b><?=count($services)?></b><span>الخدمات</span></div><div><b><?=count($portfolio)?></b><span>الأعمال</span></div><div><b><?=count($media)?></b><span>الملفات</span></div><div><b><?=count($pages)?></b><span>الصفحات</span></div></div>

<section id="design" class="panel"><div class="panel-title"><div><h2>🎨 التصميم والمظهر</h2><p>تحكم بالألوان والهيكلية والوضع الليلي.</p></div></div><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="settings"><div class="cards"><label>اسم الموقع<input name="siteName" value="<?=e($s['siteName'])?>"></label><label>الهيكلية<select name="layout"><option value="classic" <?=($s['layout']??'')==='classic'?'selected':''?>>Classic</option><option value="editorial" <?=($s['layout']??'')==='editorial'?'selected':''?>>Editorial</option><option value="portfolio" <?=($s['layout']??'')==='portfolio'?'selected':''?>>Portfolio Grid</option><option value="minimal" <?=($s['layout']??'')==='minimal'?'selected':''?>>Minimal</option></select></label><label>القائمة<select name="menuPosition"><option value="top" <?=($s['menuPosition']??'')==='top'?'selected':''?>>أعلى</option><option value="left" <?=($s['menuPosition']??'')==='left'?'selected':''?>>يسار</option><option value="right" <?=($s['menuPosition']??'')==='right'?'selected':''?>>يمين</option></select></label><label>المظهر<select name="mode"><option value="system" <?=($s['mode']??'')==='system'?'selected':''?>>Windows / System</option><option value="light" <?=($s['mode']??'')==='light'?'selected':''?>>فاتح</option><option value="dark" <?=($s['mode']??'')==='dark'?'selected':''?>>داكن</option></select></label><?php foreach(['primary','accent','lightBg','darkBg','lightText','darkText'] as $c):?><label><?=e($c)?><input type="color" name="<?=$c?>" value="<?=e($s[$c])?>"></label><?php endforeach;?><label>الشعار <input class="file-input" type="file" name="logo" accept="image/png,image/jpeg,image/webp,image/svg+xml"><span class="hint">اختر الشعار من الجهاز</span><?php if(!empty($s['logo'])):?><img class="preview-img" src="../<?=e($s['logo'])?>" alt="logo"><?php endif;?></label></div><button>حفظ التصميم</button></form></section>

<section id="home" class="panel"><div class="panel-title"><div><h2>🏠 الصفحة الرئيسية</h2></div></div><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="settings"><div class="cards"><label>الهاتف<input name="phone" value="<?=e($s['phone'])?>"></label><label>WhatsApp<input name="whatsapp" value="<?=e($s['whatsapp'])?>"></label><label>البريد<input name="email" value="<?=e($s['email'])?>"></label><label>Hero Badge عربي<input name="heroBadge_ar" value="<?=e($s['heroBadge_ar'])?>"></label><label>Hero Badge English<input name="heroBadge_en" value="<?=e($s['heroBadge_en'])?>"></label><label>العنوان الرئيسي عربي<textarea name="heroTitle_ar"><?=e($s['heroTitle_ar'])?></textarea></label><label>العنوان الرئيسي English<textarea name="heroTitle_en"><?=e($s['heroTitle_en'])?></textarea></label><label>الوصف عربي<textarea name="heroText_ar"><?=e($s['heroText_ar'])?></textarea></label><label>الوصف English<textarea name="heroText_en"><?=e($s['heroText_en'])?></textarea></label></div><button>حفظ الصفحة الرئيسية</button></form></section>

<section id="about" class="panel"><div class="panel-title"><h2>👤 من نحن</h2></div><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="about_save"><input type="hidden" name="current_image" value="<?=e($about['image']??'')?>"><div class="cards"><label>العنوان عربي<input name="title_ar" value="<?=e($about['title_ar']??'من نحن')?>"></label><label>العنوان English<input name="title_en" value="<?=e($about['title_en']??'About')?>"></label><label>المحتوى عربي<textarea name="content_ar"><?=e($about['content_ar']??'')?></textarea></label><label>المحتوى English<textarea name="content_en"><?=e($about['content_en']??'')?></textarea></label><label>صورة القسم<input class="file-input" type="file" name="file" accept="image/*"><?php if(!empty($about['image'])):?><img class="preview-img" src="../<?=e($about['image'])?>" alt="about"><?php endif;?></label></div><label><input type="checkbox" name="enabled" <?=checked($about['enabled']??1)?>> ظاهر</label><button>حفظ من نحن</button></form></section>

<section id="services" class="panel"><div class="panel-title"><h2>🧩 الخدمات</h2></div><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="service_save"><input name="title_ar" placeholder="اسم الخدمة عربي" required><input name="title_en" placeholder="English title"><input name="description_ar" placeholder="الوصف عربي"><input name="description_en" placeholder="English description"><input class="file-input" type="file" name="file" accept="image/*"><input type="number" name="sort_order" value="1"><button>＋ إضافة خدمة</button></form><?php foreach($services as $x):?><details><summary><?=e($x['title_ar'])?></summary><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="service_save"><input type="hidden" name="id" value="<?=$x['id']?>"><input type="hidden" name="current_image" value="<?=e($x['image'])?>"><input name="title_ar" value="<?=e($x['title_ar'])?>"><input name="title_en" value="<?=e($x['title_en'])?>"><input name="description_ar" value="<?=e($x['description_ar'])?>"><input name="description_en" value="<?=e($x['description_en'])?>"><input class="file-input" type="file" name="file" accept="image/*"><?php if(!empty($x['image'])):?><img class="preview-img" src="../<?=e($x['image'])?>" alt=""><?php endif;?><input type="number" name="sort_order" value="<?=$x['sort_order']?>"><label><input type="checkbox" name="enabled" <?=checked($x['enabled'])?>> ظاهر</label><button>حفظ</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="service_delete"><input type="hidden" name="id" value="<?=$x['id']?>"><button class="danger">حذف</button></form></details><?php endforeach;?></section>

<section id="portfolio" class="panel"><div class="panel-title"><h2>🖼️ الأعمال والصور</h2><p>رفع مباشر من الجهاز — لا توجد خانة لرابط الصورة.</p></div><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="portfolio_save"><input name="title" placeholder="اسم المشروع" required><input name="category" placeholder="التصنيف"><input name="description" placeholder="الوصف"><input class="file-input" type="file" name="file" accept="image/*" required><input name="url" placeholder="رابط المشروع الخارجي (اختياري)"><input type="number" name="sort_order" value="1"><label><input type="checkbox" name="enabled" checked> ظاهر</label><button>＋ إضافة عمل</button></form><?php foreach($portfolio as $x):?><details><summary><?=e($x['title'])?></summary><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="portfolio_save"><input type="hidden" name="id" value="<?=$x['id']?>"><input type="hidden" name="current_image" value="<?=e($x['image'])?>"><input name="title" value="<?=e($x['title'])?>"><input name="category" value="<?=e($x['category'])?>"><input name="description" value="<?=e($x['description'])?>"><input class="file-input" type="file" name="file" accept="image/*"><?php if(!empty($x['image'])):?><img class="preview-img" src="../<?=e($x['image'])?>" alt=""><?php endif;?><input name="url" value="<?=e($x['url'])?>" placeholder="رابط المشروع الخارجي اختياري"><input type="number" name="sort_order" value="<?=$x['sort_order']?>"><label><input type="checkbox" name="enabled" <?=checked($x['enabled'])?>> ظاهر</label><button>حفظ</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="portfolio_delete"><input type="hidden" name="id" value="<?=$x['id']?>"><button class="danger">حذف</button></form></details><?php endforeach;?></section>

<section id="media" class="panel"><div class="panel-title"><h2>📁 مدير الملفات</h2><p>كل الملفات المرفوعة من جهازك تظهر هنا.</p></div><form method="post" enctype="multipart/form-data" class="upload-box"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="media_upload"><input class="file-input" type="file" name="file" accept="image/*,.pdf" required><button>⬆ رفع من الجهاز</button></form><div class="media-grid"><?php foreach($media as $m):?><div class="media-card"><?php if(str_starts_with((string)$m['mime'],'image/')):?><img src="../<?=e($m['path'])?>" alt=""><?php else:?><div class="file-icon">PDF</div><?php endif;?><div class="media-meta"><b><?=e($m['filename'])?></b><small><?=number_format(((int)$m['size'])/1024,1)?> KB</small></div><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="media_delete"><input type="hidden" name="id" value="<?=$m['id']?>"><button class="danger">حذف</button></form></div><?php endforeach;?></div></section>

<section id="pages" class="panel"><div class="panel-title"><h2>📄 الصفحات الجانبية</h2></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="page_save"><input name="slug" placeholder="privacy" required><input name="title_ar" placeholder="العنوان عربي"><input name="title_en" placeholder="English title"><textarea name="content_ar" placeholder="المحتوى العربي"></textarea><textarea name="content_en" placeholder="English content"></textarea><input type="number" name="sort_order" value="1"><label><input type="checkbox" name="enabled" checked> ظاهر</label><button>＋ إنشاء صفحة</button></form><?php foreach($pages as $x):?><details><summary>/<?=e($x['slug'])?> — <?=e($x['title_ar'])?></summary><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="page_save"><input type="hidden" name="id" value="<?=$x['id']?>"><input name="slug" value="<?=e($x['slug'])?>"><input name="title_ar" value="<?=e($x['title_ar'])?>"><input name="title_en" value="<?=e($x['title_en'])?>"><textarea name="content_ar"><?=e($x['content_ar'])?></textarea><textarea name="content_en"><?=e($x['content_en'])?></textarea><input type="number" name="sort_order" value="<?=$x['sort_order']?>"><label><input type="checkbox" name="enabled" <?=checked($x['enabled'])?>> ظاهر</label><button>حفظ</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="page_delete"><input type="hidden" name="id" value="<?=$x['id']?>"><button class="danger">حذف</button></form></details><?php endforeach;?></section>

<section id="menus" class="panel"><div class="panel-title"><h2>☰ القوائم</h2></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="menu_save"><input name="label_ar" placeholder="اسم الرابط عربي"><input name="label_en" placeholder="English"><input name="url" placeholder="index.php#services"><select name="location"><option value="header">header</option><option value="left">left</option><option value="right">right</option><option value="footer">footer</option></select><input type="number" name="sort_order" value="1"><label><input type="checkbox" name="enabled" checked> ظاهر</label><button>＋ إضافة</button></form><?php foreach($menus as $x):?><details><summary><?=e($x['label_ar'])?> — <?=e($x['location'])?></summary><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="menu_save"><input type="hidden" name="id" value="<?=$x['id']?>"><input name="label_ar" value="<?=e($x['label_ar'])?>"><input name="label_en" value="<?=e($x['label_en'])?>"><input name="url" value="<?=e($x['url'])?>"><select name="location"><?php foreach(['header','left','right','footer'] as $loc):?><option value="<?=$loc?>" <?=$x['location']===$loc?'selected':''?>><?=$loc?></option><?php endforeach;?></select><input type="number" name="sort_order" value="<?=$x['sort_order']?>"><label><input type="checkbox" name="enabled" <?=checked($x['enabled'])?>> ظاهر</label><button>حفظ</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="menu_delete"><input type="hidden" name="id" value="<?=$x['id']?>"><button class="danger">حذف</button></form></details><?php endforeach;?></section>

<section id="social" class="panel"><div class="panel-title"><h2>🔗 السوشيال</h2></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="social_save"><input name="name" placeholder="Instagram"><input name="url" placeholder="https://..."><input name="icon" placeholder="instagram"><input type="number" name="sort_order" value="1"><label><input type="checkbox" name="enabled" checked> ظاهر</label><button>＋ إضافة</button></form><?php foreach($socials as $x):?><details><summary><?=e($x['name'])?></summary><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="social_save"><input type="hidden" name="id" value="<?=$x['id']?>"><input name="name" value="<?=e($x['name'])?>"><input name="url" value="<?=e($x['url'])?>"><input name="icon" value="<?=e($x['icon'])?>"><input type="number" name="sort_order" value="<?=$x['sort_order']?>"><label><input type="checkbox" name="enabled" <?=checked($x['enabled'])?>> ظاهر</label><button>حفظ</button></form><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="social_delete"><input type="hidden" name="id" value="<?=$x['id']?>"><button class="danger">حذف</button></form></details><?php endforeach;?></section>
</main></div></body></html>
