<?php
$lang=(($_GET['lang']??'ar')==='en')?'en':'ar';
$base = str_ends_with($_SERVER['SCRIPT_NAME'] ?? '', '/admin/index.php') ? '../' : '';
$menus=$menus??db()->query("SELECT * FROM menu_items WHERE enabled=1 AND location='header' ORDER BY sort_order,id")->fetchAll();
$logo=setting('logo');
$logoSrc=$logo ? $base.e($logo) : $base.'assets/logo-dark.png';
function nav_href(string $url,string $base): string { if(preg_match('~^https?://~i',$url)) return $url; return $base.ltrim($url,'/'); }
?>
<!doctype html><html lang="<?=e($lang)?>" dir="<?=$lang==='ar'?'rtl':'ltr'?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?=e(setting($lang==='ar'?'heroText_ar':'heroText_en'))?>"><title><?=e(setting('siteName','Thaer Media'))?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;600;700;800;900&family=Expo+Arabic:wght@400;500;600;700;800;900&family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&family=Tajawal:wght@400;500;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="<?=$base?>assets/css/site.css"><style>:root{--green:<?=e(setting('green','#0f4a46'))?>;--green2:<?=e(setting('green2','#092f32'))?>;--navy:<?=e(setting('navy','#09204e'))?>;--gold:<?=e(setting('gold','#e2b960'))?>;--white:<?=e(setting('white','#f5f5f2'))?>;--muted:<?=e(setting('muted','#b9c7c5'))?>;--primary:<?=e(setting('primary','#0f4a46'))?>;--accent:<?=e(setting('accent','#e2b960'))?>;--light:<?=e(setting('lightBg','#f5f5f2'))?>;--dark:<?=e(setting('darkBg','#061d25'))?>;--lt:<?=e(setting('lightText','#163b38'))?>;--dt:<?=e(setting('darkText','#f5f5f2'))?>;--font-color:<?=e(setting('fontColor','#f5f5f2'))?>;--site-font:'<?=e(setting('fontFamily','Expo Arabic'))?>',Arial,sans-serif}body{font-family:var(--site-font);color:var(--font-color)}</style></head><body class="layout-<?=e(setting('layout','classic'))?> mode-<?=e(setting('mode','system'))?> menu-<?=e(setting('menuPosition','top'))?> <?= $lang==='en'?'en-mode':'' ?>"><div class="ambient ambient-a"></div><div class="ambient ambient-b"></div>
<header class="nav glass" id="top"><div class="nav-inner"><a class="logo-link" href="<?=$base?>index.php" aria-label="Thaer Media"><img src="<?=$logoSrc?>" alt="<?=e(setting('siteName','Thaer Media'))?>"></a><nav class="desktop-nav" aria-label="Main navigation"><?php foreach($menus as $m):?><a href="<?=e(nav_href($m['url']??'',$base))?>"><?=e($lang==='ar'?$m['label_ar']:$m['label_en'])?></a><?php endforeach;?></nav><div class="nav-actions"><button id="langBtn" class="lang" type="button"><?=$lang==='ar'?'EN':'AR'?></button><a class="btn btn-gold nav-cta" href="<?=$base?>contact.php?lang=<?=$lang?>"><?=$lang==='ar'?'احجز استشارتك':'Book a Consultation'?></a><button class="menu-btn" id="menuBtn" type="button" aria-label="فتح القائمة">☰</button></div></div><div class="mobile-nav" id="mobileNav"><?php foreach($menus as $m):?><a href="<?=e(nav_href($m['url']??'',$base))?>"><?=e($lang==='ar'?$m['label_ar']:$m['label_en'])?></a><?php endforeach;?></div></header>
